// <auto-generated-like> Manually added to map CustomerRequirements table. </auto-generated-like>
namespace DAL.Models;

public class CustomerRequirement
{
    public int RequirementId { get; set; }
    public int UserId { get; set; }
    public string CustomerName { get; set; } = string.Empty;
    public string Phone { get; set; } = string.Empty;
    public string Content { get; set; } = string.Empty;
    public DateTime? RequestDate { get; set; }
    public int StatusId { get; set; }

    public virtual RequirementStatus Status { get; set; } = null!;
    public virtual User User { get; set; } = null!;
}


