// <auto-generated-like> Manually added to map RequirementStatus table. </auto-generated-like>
namespace DAL.Models;

public class RequirementStatus
{
    public int StatusId { get; set; }
    public string StatusName { get; set; } = string.Empty;

    public virtual ICollection<CustomerRequirement> CustomerRequirements { get; set; } = new List<CustomerRequirement>();
}


